
// eslint-disable-line no-use-before-define

export const storeProducts = [
  {
    id: 1,
    title: "Air Max 95 - Black",
    img: "brands/nike/shoes/blk-air-max-95.jpg",
    price: 3200,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Air Max Korea",
    img: "brands/nike/shoes/air-max-95-korea.jpg",
    price: 2500,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Air Max 97 - White",
    img: "brands/nike/shoes/wht-air-max.jpg",
    price: 2500,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Air Jordan 1",
    img: "brands/nike/shoes/orng-air-jordan-1.jpg",
    price: 2000,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0, 
    total: 0,
  },
  {
    id: 5,
    title: "Air Jordan 1",
    img: "brands/nike/shoes/red-air-jordan-1.jpg",
    price: 2000,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Air Force 1",
    img: "brands/nike/shoes/wht-air-force-1.jpg",
    price: 1600,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Air Jordan low",
    img: "brands/nike/shoes/blk-air-jordan-1-low.jpg",
    price: 1800,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Air Max Plus",
    img: "brands/nike/shoes/orng-air-max-plus.jpg",
    price: 2600,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
    id: 9,
    title: "Air Max 720",
    img: "brands/nike/shoes/air-max-720.jpg",
    price: 2100,
    size:" UK : 3, 4, 5, 6, 7, 8, 9, 10, 11",
    company: "NIKE",
    info:"Walk in closet.com",
    inCart: false,
    sizes: 0,
    count: 0,
    total: 0,
};
